Add rio

diff --git a/build/MakefileBase b/build/MakefileBase
--- a/build/MakefileBase
+++ b/build/MakefileBase
@@ -17,7 +17,7 @@ base_no_miri_no_clippy: lint_no_clippy test allowlist
 lint_unsafe:
 	cargo clippy
 	@if [ "$$(cargo clippy 2>&1 | grep -v Finished | grep -v Checking | grep -v Blocking)" ]; \
-		then echo "ERROR: `cargo clippy` found some issues (see aove)"; exit 1; \
+		then echo "ERROR: 'cargo clippy' found some issues (see above)"; exit 1; \
 	fi
 
 	cargo fmt -- --check
@@ -25,7 +25,7 @@ lint_unsafe:
 lint_unsafe_no_std:
 	cargo clippy
 	@if [ "$$(cargo clippy 2>&1 | grep -v Finished | grep -v Checking | grep -v Blocking)" ]; \
-		then echo "ERROR: `cargo clippy` found some issues (see aove)"; exit 1; \
+		then echo "ERROR: 'cargo clippy' found some issues (see above)"; exit 1; \
 	fi
 
 	cargo fmt -- --check
@@ -38,7 +38,7 @@ lint_unsafe_no_std:
 lint: lint_no_clippy
 	cargo clippy
 	@if [ "$$(cargo clippy 2>&1 | grep -v Finished | grep -v Checking | grep -v Blocking)" ]; \
-		then echo "ERROR: `cargo clippy` found some issues (see aove)"; exit 1; \
+		then echo "ERROR: `cargo clippy` found some issues (see above)"; exit 1; \
 	fi
 
 lint_no_clippy:
